import Head from "next/head";
import Link from "next/link";
import Image from "next/image";
import { getPosts } from "../utils/post";
import { useState, useEffect } from "react";

export default function Home() {
  const [posts, setPosts] = useState([]);

  useEffect(() => {
    const posts = async () => {
      setPosts(await getPosts());
    };

    posts();
  }, []);

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {posts.map((post) => {
        return <div>{post.title}</div>;
      })}
    </div>
  );
}
